device: 0

misc:
  seed: 0

experiment:
  input_resolution: [224, 224]
  dropout: 0.05
  text_length: 77
  nitc_ratio: 1.0
  ritc_eps: 1.0e-2

loss:
  weights:
    global_align: 1.0
    local_align: 1.0
    id: 0.5
    cls_view: 0.5
    id_adv: 0.5
    dec: 0.5
    vis: 0.5

schedule:
  lr: 1.0e-4
  epoch: 10
  epoch_warmup: 1
  lr_start: 1.0e-6
  lr_end: 5.0e-6
  weight_decay: 0.02
  betas: [0.9, 0.98]
  eps: 1.0e-8
  ratio_factor: 1.0

model:
  ckpt_type: original_clip
  #ckpt_type: saved
  resume: false
  saved_path: "ckpts/"
  checkpoint: "/home/u2024218474/jupyterlab/TAG-PR/ViT-B-16.pt"
  use_gather: true
  softlabel_ratio: 0.5
  embed_dim: 512
  vocab_size: 49408
  use_cap_view_decoupling: true
  use_view_loss: true
  use_dec_loss: true
  use_vis_alignment: true
  grl_lambda: 1.0
  cap_heads: 8
  view_heads: 8
  alpha_inv: 0.5
  beta_sp: 0.5


  baseline:
    global_align: true
    local_align: true
    id_loss: true

log:
  print_period: 50

data:
  batch_size: 320
  test_batch_size: 1024
  num_workers: 6

distributed:
  enabled: false
  backend: nccl
  url: "env://"

anno_dir: "/home/u2024218474/jupyterlab/TAG-PR/dataset/anno_dir"
image_dir: "/home/u2024218474/jupyterlab/TAG-PR/dataset/images"
